config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]

  # get 'sign_up' => 'users#new'
  # get 'log_out' => 'sessions#destroy'
  # get 'log_in' => 'sessions#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Извечные вопросы бытия</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title"><%= link_to "Извечные вопросы бытия", root_path %></h1>
        </div>

        <div class="header-nav">
          <% if current_user %>
            <%= link_to "@#{current_user.username}", user_path(current_user) %> |
            <%= link_to 'Выйти', session_path, data: {method: :delete} %>
          <% else %>
            <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
            <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="content">
      <div class="container">

        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>

  </body>
</html>